config/routes.rb
Vsmembership::Application.routes.draw do
  resources :feedbacks

  resources :config_settings

  resources :distributions

  resources :taxes

  resources :fees

  resources :clinics
  resources :reports, :except => [:new, :create, :delete]
  resources :models, :except => [:index, :new, :create, :delete]
  resources :membership_fees do
    get :autocomplete_clinic_name, :on => :collection
  end
  
  resources :securities
  
  root :to => "home#index"
end

app/models/tax.rb
class Tax < ActiveRecord::Base
end

app/controllers/taxes_controller.rb
class TaxesController < ApplicationController
  before_action :set_tax, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /taxes
  # GET /taxes.json
  def index
    @taxes = Tax.all
  end

  # GET /taxes/1
  # GET /taxes/1.json
  def show
  end

  # GET /taxes/new
  def new
    @tax = Tax.new
  end

  # GET /taxes/1/edit
  def edit
  end

  # POST /taxes
  # POST /taxes.json
  def create
    @tax = Tax.new(tax_params)

    respond_to do |format|
      if @tax.save
        format.html { redirect_to @tax, notice: 'Tax was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tax }
      else
        format.html { render action: 'new' }
        format.json { render json: @tax.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taxes/1
  # PATCH/PUT /taxes/1.json
  def update
    respond_to do |format|
      if @tax.update(tax_params)
        format.html { redirect_to @tax, notice: 'Tax was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tax.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxes/1
  # DELETE /taxes/1.json
  def destroy
    @tax.destroy
    respond_to do |format|
      format.html { redirect_to taxes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tax
      @tax = Tax.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tax_params
      params.require(:tax).permit(:province, :rate)
    end
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/views/taxes/_form.html.haml
= form_for @tax do |f|
  - if @tax.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tax.errors.count, "error")} prohibited this tax from being saved:"
      %ul
        - @tax.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :province
    = f.text_field :province
  .field
    = f.label :rate
    = f.text_field :rate
  .actions
    = f.submit 'Save'

app/views/taxes/edit.html.haml
%h1 Editing tax

= render 'form'

= link_to 'Show', @tax
\|
= link_to 'Back', taxes_path

app/views/taxes/index.html.haml
%h1 Listing taxes

%table
  %tr
    %th Province
    %th Rate
    %th
    %th
    %th

  - @taxes.each do |tax|
    %tr
      %td= tax.province
      %td= tax.rate
      %td= link_to 'Show', tax
      %td= link_to 'Edit', edit_tax_path(tax)
      %td= link_to 'Destroy', tax, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tax', new_tax_path

app/views/taxes/new.html.haml
%h1 New tax

= render 'form'

= link_to 'Back', taxes_path

app/views/taxes/show.html.haml
%p#notice= notice

%p
  %b Province:
  = @tax.province
%p
  %b Rate:
  = @tax.rate

= link_to 'Edit', edit_tax_path(@tax)
\|
= link_to 'Back', taxes_path