config/routes.rb
Vsmembership::Application.routes.draw do
  resources :feedbacks

  resources :config_settings

  resources :distributions

  resources :taxes

  resources :fees

  resources :clinics
  resources :reports, :except => [:new, :create, :delete]
  resources :models, :except => [:index, :new, :create, :delete]
  resources :membership_fees do
    get :autocomplete_clinic_name, :on => :collection
  end
  
  resources :securities
  
  root :to => "home#index"
end

app/models/fee.rb
class Fee < ActiveRecord::Base
  has_many :clinics, :foreign_key => 'model_id'
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /fees
  # GET /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1
  # GET /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees
  # POST /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: 'Fee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fee }
      else
        format.html { render action: 'new' }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: 'Fee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fee_params
      params.require(:fee).permit(:from, :to, :fee)
    end
    
    
    def validate_user
      logged_in = session[:logged_in]
      logger.debug("validate user")
      if logged_in == nil || logged_in != "admin"
        redirect_to "/admin.html"
        return false
      else
        logger.debug("session: " + logged_in)
      end
      return true
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/views/fees/_form.html.haml
= form_for @fee do |f|
  - if @fee.errors.any?
    #error_explanation
      %h2= "#{pluralize(@fee.errors.count, "error")} prohibited this fee from being saved:"
      %ul
        - @fee.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :from
    = f.text_field :from
  .field
    = f.label :to
    = f.text_field :to
  .field
    = f.label :fee
    = f.text_field :fee
  .actions
    = f.submit 'Save'

app/views/fees/edit.html.haml
%h1 Editing fee

= render 'form'

= link_to 'Show', @fee
\|
= link_to 'Back', fees_path

app/views/fees/index.html.haml
%h1 Listing fees

%table
  %tr
    %th From
    %th To
    %th Fee
    %th
    %th
    %th

  - @fees.each do |fee|
    %tr
      %td= fee.from
      %td= fee.to
      %td= fee.fee
      %td= link_to 'Show', fee
      %td= link_to 'Edit', edit_fee_path(fee)
      %td= link_to 'Destroy', fee, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Fee', new_fee_path

app/views/fees/new.html.haml
%h1 New fee

= render 'form'

= link_to 'Back', fees_path

app/views/fees/show.html.haml
%p#notice= notice

%p
  %b From:
  = @fee.from
%p
  %b To:
  = @fee.to
%p
  %b Fee:
  = @fee.fee

= link_to 'Edit', edit_fee_path(@fee)
\|
= link_to 'Back', fees_path